### ISSUE TITLE
Support v2.1 pgr_alphaShape/pgr_pointsAsPolygon (alpha value and hole polygon)

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgRoutingLayer#1]
Next pgRouting release will include alpha shape hole polygon case (https://github.com/pgRouting/pgrouting/issues/235),
so supporting it will be necessary.

Currently, the following error occurs in hole polygon case.
<pre>
Traceback (most recent call last):
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/pgRoutingLayer.py", line 391, in run
    function.draw(rows, con, args, geomType, self.canvasItemList, self.iface.mapCanvas())
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/functions/alphashape.py", line 88, in draw
    pt = QgsPoint(x, y)
TypeError: arguments did not match any overloaded call:
  QgsPoint(): too many arguments
  QgsPoint(QgsPoint): argument 1 has unexpected type 'NoneType'
  QgsPoint(float, float): argument 1 has unexpected type 'NoneType'
</pre>

**Comment by sanak** [comment]
Supported alpha shape hole polygon case by the following commit.
https://github.com/pgRouting/pgRoutingLayer/commit/fad8b77d715293c40f104330d6901f7519289466
* Rubber band don't support hole polygon, so write following log message.
<pre>
Alpha shape result geometry is MultiPolygon or has holes.
Please click [Export] button to see complete result.
</pre>
