### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'pgRoutingLayer'


### ISSUE THREAD

**Issue by sandydev29** [pgRouting/pgRoutingLayer#134]
Couldn't load plugin 'pgRoutingLayer-develop' due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Sandesh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer-develop\__init__.py", line 29, in classFactory
    from pgRoutingLayer.pgRoutingLayer import PgRoutingLayer
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pgRoutingLayer'

```
pgRoutingLayer-develop 3.0.0, QGIS 3.16.1-Hannover on Windows 7

**Comment by cayetanobv** [comment]
Hi @sandydev29 . The plugin folder name must be `pgRoutingLayer`. If you cnahge that you could avoid this error.

**Comment by sandydev29** [comment]
These type  error occurs during install the other plugin.

**Comment by cayetanobv** [comment]
How are you installing the plugin?
