### ISSUE TITLE
Tisler upgrade broke pgRoutingLayer plugin

### ISSUE THREAD

**Issue by geojochen** [pgRouting/pgRoutingLayer#138]
pgRoutingLayer works fine for me with and until QGIS version 3.22
Upon upgrading to 3.24, I get the following error right while starting v3.24 (apparently, the getapi() function is deprecated):

Couldn't load plugin 'pgRoutingLayer' due to an error when calling its initGui() method 
ValueError: unknown API 'QVariant' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~2.2/apps/qgis/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 240, in initGui
    self.reloadConnections()
  File "C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 272, in reloadConnections
    db = self.actionsDb[dbname].connect()
  File "C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\dbConnection.py", line 152, in connect
    conn = ConnectionManager.getConnection(self.type).connect(selected, self.parent())
  File "C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\connectors\postgis.py", line 132, in connect
    service, host, port, database, username, password = list(map(get_value_str, ["service", "host", "port", "database", "username", "password"]))
  File "C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\connectors\postgis.py", line 131, in 
    get_value_str = lambda x: str(settings.value(x) if Utils.isSIPv2() else settings.value(x).toString())
  File "C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\pgRoutingLayer_utils.py", line 77, in isSIPv2
    return sip.getapi('QVariant') > 1
ValueError: unknown API 'QVariant'

**Comment by blewsky** [comment]
Same here

**Comment by sanak** [comment]
@geojochen @blewsky (CC: @cvvergara, @cayetanobv)
Thanks for reporting this issue.

From the following error log,
```
"C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\pgRoutingLayer_utils.py", line 77, in isSIPv2
return sip.getapi('QVariant') > 1
ValueError: unknown API 'QVariant'
```

this issue's cause seems to be my old (QGIS v1 & v2) supporting time one...
https://github.com/pgRouting/pgRoutingLayer/commit/e126ca1bf938be1e8fd688669d1c0207605a6b09

We already dropped QGIS < v3, so I will try to fix those part.
https://github.com/pgRouting/pgRoutingLayer/blob/master/metadata.txt#L11
```
qgisMinimumVersion=3.0
```

**Comment by sanak** [comment]
@geojochen @blewsky
We just published pgRoutingLayer `3.0.2`, so could you upgrade the plugin ?
Thanks,

**Comment by blewsky** [comment]
Hi @sanak ,
Thanks a lot . I upgraded and it worked. 👍

**Comment by sanak** [comment]
@blewsky Okay, thanks for confirmation!
