### ISSUE TITLE
Connection error after upgrading to the latest master

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgRoutingLayer#17]
Here is the error message.
<pre>
Couldn't load plugin pgRoutingLayer due to an error when calling its initGui() method

Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 228, in startPlugin
    plugins[packageName].initGui()
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/pgRoutingLayer.py", line 181, in initGui
    self.reloadConnections()
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/pgRoutingLayer.py", line 236, in reloadConnections
    db = self.actionsDb[dbname].connect()
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/dbConnection.py", line 129, in connect
    conn = ConnectionManager.getConnection( self.type ).connect( selected, self.parent() )
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/connectors/postgis.py", line 135, in connect
    return Connection(uri)
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/connectors/postgis.py", line 153, in __init__
    raise DbError(e)
DbError: FATAL:  role "NULL" does not exist

Python version:
2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]

QGIS version:
2.8.4-Wien Wien, exported
</pre>

**Comment by sanak** [comment]
This issue cause was attempting to connect non-existence db (in QGIS connection settings).
I fixed this issue on "develop" branch with above commit.
