### ISSUE TITLE
TSP (euclid) annotation deleted error

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgRoutingLayer#20]
After executing TSP (euclid) function, then close QGIS project,
I got the following error.

<pre>
Error while unloading plugin pgRoutingLayer

Traceback (most recent call last):
  File "/usr/local/Cellar/qgis-28/2.8.9/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 270, in unloadPlugin
    plugins[packageName].unload()
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/pgRoutingLayer.py", line 217, in unload
    self.clear()
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/pgRoutingLayer.py", line 858, in clear
    anno.setVisible(False)
RuntimeError: wrapped C/C++ object of type QgsTextAnnotationItem has been deleted

Python version:
2.7.12 (default, Jun 29 2016, 14:04:44) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]

QGIS version:
2.8.9-Wien Wien, exported
</pre>

**Comment by sanak** [comment]
I also confirmed that "tsp(euclid)" - "Clear preview" doesn't clear rubber band.

**Comment by sanak** [comment]
I fixed this issue by above commit.
