### ISSUE TITLE
QGIS 1.8 version log output error

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgRoutingLayer#21]
When I use QGIS 1.8 version, the following error occurred.
<pre>
pgRoutingLayerプラグインをロードできませｎでしたは内部でclassFactory()メソッドを呼び出し中にエラーが発生しました

Traceback (most recent call last):
  File "C:/PROGRA~2/Quantum GIS Lisboa/apps/qgis/./python\qgis\utils.py", line 164, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/sanak/.qgis//python/plugins\pgRoutingLayer\__init__.py", line 35, in classFactory
    from pgRoutingLayer import PgRoutingLayer
  File "C:/PROGRA~2/Quantum GIS Lisboa/apps/qgis/./python\qgis\utils.py", line 309, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/sanak/.qgis//python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 28, in 
    import dbConnection
  File "C:/PROGRA~2/Quantum GIS Lisboa/apps/qgis/./python\qgis\utils.py", line 309, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/sanak/.qgis//python/plugins\pgRoutingLayer\dbConnection.py", line 7, in 
    import pgRoutingLayer_utils as Utils
  File "C:/PROGRA~2/Quantum GIS Lisboa/apps/qgis/./python\qgis\utils.py", line 309, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/sanak/.qgis//python/plugins\pgRoutingLayer\pgRoutingLayer_utils.py", line 97, in 
    def logMessage(message, level=QgsMessageLog.INFO):
AttributeError: type object 'QgsMessageLog' has no attribute 'INFO'

Pythonバージョン:
2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]

QGISバージョン:
1.8.0-Lisboa Lisboa, f440b60
</pre>

**Comment by cvvergara** [comment]
I asked on qgis the following:
http://irclogs.geoapt.com/qgis/%23qgis.2016-07-08.log
the current qgis is 2.8 so I ask, are we going to support 1.8?

The lines about 
```
 def logMessage(message, level=QgsMessageLog.INFO):
```
is here:
https://github.com/pgRouting/pgRoutingLayer/blob/develop/pgRoutingLayer_utils.py#L97

and I went to see the documentation:
https://qgis.org/api/classQgsMessageLog.html

maybe
```
#include <qgsmessagelog.h>
```
is missing?

**Comment by sanak** [comment]
The error disappeared by adding the following lines to `pgRoutingLayer_utils.py`.
<pre>
# Support for QGIS 1.8
QgsMessageLog.INFO = 0
QgsMessageLog.WARNING = 1
QgsMessageLog.CRITICAL = 2
</pre>
But I confirmed another "Export" function error on QGIS 1.8.0 Windows,
and fixing it seemed to be difficult...
So, let's drop QGIS 1.8 support by modifying "metadata.txt" - `qgisMinimumVersion` from 1.8 to 2.0.

**Comment by cvvergara** [comment]
Not fixing
