### ISSUE TITLE
Unassigned 'db' variable error

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgRoutingLayer#24]
After removing QGIS connection database directly (by `dropdb`),
I encountered the following error.
<pre>
Couldn't load plugin pgRoutingLayer due to an error when calling its initGui() method

Traceback (most recent call last):
  File "/usr/local/Cellar/qgis-28/2.8.9/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 228, in startPlugin
    plugins[packageName].initGui()
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/pgRoutingLayer.py", line 181, in initGui
    self.reloadConnections()
  File "/Users/sanak/.qgis2/python/plugins/pgRoutingLayer/pgRoutingLayer.py", line 246, in reloadConnections
    if db and db.con:
UnboundLocalError: local variable 'db' referenced before assignment
</pre>

pgRoutingLayer.py line 246 is:
https://github.com/pgRouting/pgRoutingLayer/blob/develop/pgRoutingLayer.py#L246

I guess that `db = None` or some other line is necessary before `try` block.
(Also, other `finally` parts.)

**Comment by sanak** [comment]
I fixed this issue on "develop" branch directly.
