### ISSUE TITLE
Plugin not loading after upgrade to pgRouting 2.1.0

### ISSUE THREAD

**Issue by copossum** [pgRouting/pgRoutingLayer#43]
When starting QGis, pgRoutingLayer produces the error message stated below. It used to work fine until I upgraded to pgRouting 2.1.0. The database is Postgres 9.5 with PostGis 2.2.1 running on Ubuntu 16.
The database encoding is UTF-8.

Couldn't load plugin pgRoutingLayer due to an error when calling its initGui() method 

UnicodeDecodeError: 'utf8' codec can't decode byte 0x84 in position 18: invalid start byte 
Traceback (most recent call last):
  File "E:/Software/QGISLA~1/apps/qgis/./python/qgis/utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/username/.qgis2/python/plugins/pgRoutingLayer/pgRoutingLayer.py", line 209, in initGui
    self.reloadConnections()
  File "C:/Users/username/.qgis2/python/plugins/pgRoutingLayer/pgRoutingLayer.py", line 239, in reloadConnections
    db = self.actionsDb[dbname].connect()
  File "C:/Users/username/.qgis2/python/plugins/pgRoutingLayer/dbConnection.py", line 129, in connect
    conn = ConnectionManager.getConnection( self.type ).connect( selected, self.parent() )
  File "C:/Users/username/.qgis2/python/plugins/pgRoutingLayer/connectors/postgis.py", line 139, in connect
    return Connection(uri)
  File "C:/Users/username/.qgis2/python/plugins/pgRoutingLayer/connectors/postgis.py", line 155, in __init__
    raise DbError(e)
  File "C:/Users/username/.qgis2/python/plugins/pgRoutingLayer/connectors/postgis.py", line 77, in __init__
    msg = unicode( error.args[0], 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0x84 in position 18: invalid start byte

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.1 Las Palmas, 3e73840

**Comment by cvvergara** [comment]
maybe its related to this one: #39 
Can you upgrade to 2.2.2 and try again please

**Comment by cvvergara** [comment]
Please reopen a new issue if problem persists on pgRoutingLayer v3.0.0
